apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "marge.fullname"  . }}-config
  labels:
    {{- include "marge.labels" . | nindent 4 }}
data:
  {{- if .Values.config }}
  marge-bot-config.yaml: {{ .Values.config | quote }}
  {{- end }}
  {{- if not (include "marge.manageSecret" .) }}
  gitlab-url: {{ .Values.secret.gitlabUrl | quote }}
  {{- end }}
  sitecustomize.py: |
    import ssl
    try:
        _create_unverified_https_context = ssl._create_unverified_context
    except AttributeError:
        pass
    else:
        ssl._create_default_https_context = _create_unverified_https_context
