{{- if .Values.secret.externalSecret.enabled -}}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "marge.fullname" . }}-external-secret
  labels:
    {{- include "marge.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.secret.externalSecret.refreshInterval | default "1h" }}
  secretStoreRef:
    name: {{ .Values.secret.externalSecret.secretStoreRef.name }}
    kind: {{ .Values.secret.externalSecret.secretStoreRef.kind }}
  target:
    name: {{ if .Values.secret.externalSecret.target }}{{ .Values.secret.externalSecret.target.name | default (printf "%s-secret" (include "marge.fullname" .)) }}{{ else }}{{ printf "%s-secret" (include "marge.fullname" .) }}{{ end }}
    creationPolicy: {{ if .Values.secret.externalSecret.target }}{{ .Values.secret.externalSecret.target.creationPolicy | default "Owner" }}{{ else }}Owner{{ end }}
  data:
    {{- if .Values.secret.externalSecret.data }}
    {{- toYaml .Values.secret.externalSecret.data | nindent 4 }}
    {{- end }}
{{- end }}
