{{- if and (not .Values.secret.existingSecret) (not .Values.secret.externalSecret.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "marge.secretName" . }}
  labels:
    {{- include "marge.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.secret.keys.gitlabUrl }}: {{ .Values.secret.gitlabUrl | b64enc | quote }}
  {{ .Values.secret.keys.sshKey }}: {{ .Values.secret.sshKey | quote }}
  {{ .Values.secret.keys.authToken }}: {{ .Values.secret.authToken | b64enc | quote }}
{{- end }}
