apiVersion: v2
appVersion: 0.16.0
description: Marge-bot is a merge-bot for GitLab
home: https://github.com/hiboxsystems/marge-bot
icon: https://upload.wikimedia.org/wikipedia/en/0/0b/Marge_Simpson.png
keywords:
- merge
- marge
- bot
- gitlab
maintainers:
- name: zsozso
  url: https://github.com/zsozso/marge-bot-helm
name: marge-bot
type: application
version: 1.3.2
